package com.beepiz.blegattcoroutines.genericaccess

/**
 * Constants definitions from [official docs](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.gap.appearance.xml).
 */
object Appearance {
    const val UNKNOWN: Short = 0
    const val GENERIC_PHONE: Short = 64 // Generic category
    const val GENERIC_COMPUTER: Short = 128 // Generic category
    const val GENERIC_WATCH: Short = 192 // Generic category
    const val WATCH_SPORTS: Short = 193 // Watch subtype
    const val GENERIC_CLOCK: Short = 256 // Generic category
    const val GENERIC_DISPLAY: Short = 320 // Generic category
    const val GENERIC_REMOTE_CONTROL: Short = 384 // Generic category
    const val GENERIC_EYE_GLASSES: Short = 448 // Generic category
    const val GENERIC_TAG: Short = 512 // Generic category
    const val GENERIC_KEYRING: Short = 576 // Generic category
    const val GENERIC_MEDIA_PLAYER: Short = 640 // Generic category
    const val GENERIC_BARCODE_SCANNER: Short = 704 // Generic category
    const val GENERIC_THERMOMETER: Short = 768 // Generic category
    const val THERMOMETER_EAR: Short = 769 // Thermometer subtype
    const val GENERIC_HEART_RATE_SENSOR: Short = 832 // Generic category
    const val HEART_RATE_BELT: Short = 833 // Heart Rate Sensor subtype
    const val GENERIC_BLOOD_PRESSURE: Short = 896 // Generic category
    const val BLOOD_PRESSURE_ARM: Short = 897 // Blood Pressure subtype
    const val BLOOD_PRESSURE_WRIST: Short = 898 // Blood Pressure subtype
    const val HUMAN_INTERFACE_DEVICE: Short = 960 // HID Generic
    const val KEYBOARD: Short = 961 // HID subtype
    const val MOUSE: Short = 962 // HID subtype
    const val JOYSTICK: Short = 963 // HID subtype
    const val GAMEPAD: Short = 964 // HID subtype
    const val DIGITIZER_TABLET: Short = 965 // HID subtype
    const val CARD_READER: Short = 966 // HID subtype
    const val DIGITAL_PEN: Short = 967 // HID subtype
    const val BARCODE_SCANNER: Short = 968 // HID subtype
    const val GENERIC_GLUCOSE_METER: Short = 1024 // Generic category
    const val GENERIC_RUNNING_WALKING_SENSOR: Short = 1088 // Generic category
    const val IN_SHOE_RUNNING_WALKING_SENSOR: Short = 1089 // Running Walking Sensor subtype
    const val ON_SHOE_RUNNING_WALKING_SENSOR: Short = 1090 // Running Walking Sensor subtype
    const val ON_HIP_RUNNING_WALKING_SENSOR: Short = 1091 // Running Walking Sensor subtype
    const val GENERIC_CYCLING: Short = 1152 // Generic category
    const val CYCLING_COMPUTER: Short = 1153 // Cycling subtype
    const val CYCLING_SPEED_SENSOR: Short = 1154 // Cycling subtype
    const val CYCLING_CADENCE_SENSOR: Short = 1155 // Cycling subtype
    const val CYCLING_POWER_SENSOR: Short = 1156 // Cycling subtype
    const val CYCLING_SPEED_AND_CADENCE_SENSOR: Short = 1157 // Cycling subtype
    const val GENERIC_CONTROL_DEVICE: Short = 1216 // Generic category
    const val SWITCH: Short = 1217 // Control Device subtype
    const val MULTI_SWITCH: Short = 1218 // Control Device subtype
    const val BUTTON: Short = 1219 // Control Device subtype
    const val SLIDER: Short = 1220 // Control Device subtype
    const val ROTARY: Short = 1221 // Control Device subtype
    const val TOUCH_PANEL: Short = 1222 // Control Device subtype
    const val GENERIC_NETWORK_DEVICE: Short = 1280 // Generic category
    const val ACCESS_POINT: Short = 1281 // Generic Network subtype
    const val GENERIC_SENSOR: Short = 1344 // Generic category
    const val MOTION_SENSOR: Short = 1345 // Sensor subtype
    const val AIR_QUALITY_SENSOR: Short = 1346 // Sensor subtype
    const val TEMPERATURE_SENSOR: Short = 1347 // Sensor subtype
    const val HUMIDITY_SENSOR: Short = 1348 // Sensor subtype
    const val LEAK_SENSOR: Short = 1349 // Sensor subtype
    const val SMOKE_SENSOR: Short = 1350 // Sensor subtype
    const val OCCUPANCY_SENSOR: Short = 1351 // Sensor subtype
    const val CONTACT_SENSOR: Short = 1352 // Sensor subtype
    const val CARBON_MONOXIDE_SENSOR: Short = 1353 // Sensor subtype
    const val CARBON_DIOXIDE_SENSOR: Short = 1354 // Sensor subtype
    const val AMBIENT_LIGHT_SENSOR: Short = 1355 // Sensor subtype
    const val ENERGY_SENSOR: Short = 1356 // Sensor subtype
    const val COLOR_LIGHT_SENSOR: Short = 1357 // Sensor subtype
    const val RAIN_SENSOR: Short = 1358 // Sensor subtype
    const val FIRE_SENSOR: Short = 1359 // Sensor subtype
    const val WIND_SENSOR: Short = 1360 // Sensor subtype
    const val PROXIMITY_SENSOR: Short = 1361 // Sensor subtype
    const val MULTI_SENSOR: Short = 1362 // Sensor subtype
    const val GENERIC_LIGHT_FIXTURES: Short = 1408 // Generic category
    const val WALL_LIGHT: Short = 1409 // Light Fixture subtype
    const val CEILING_LIGHT: Short = 1410 // Light Fixture subtype
    const val FLOOR_LIGHT: Short = 1411 // Light Fixture subtype
    const val CABINET_LIGHT: Short = 1412 // Light Fixture subtype
    const val DESK_LIGHT: Short = 1413 // Light Fixture subtype
    const val TROFFER_LIGHT: Short = 1414 // Light Fixture subtype
    const val PENDANT_LIGHT: Short = 1415 // Light Fixture subtype
    const val IN_GROUND_LIGHT: Short = 1416 // Light Fixture subtype
    const val FLOOD_LIGHT: Short = 1417 // Light Fixture subtype
    const val UNDERWATER_LIGHT: Short = 1418 // Light Fixture subtype
    const val BOLLARD_WITH_LIGHT: Short = 1419 // Light Fixture subtype
    const val PATHWAY_LIGHT: Short = 1420 // Light Fixture subtype
    const val GARDEN_LIGHT: Short = 1421 // Light Fixture subtype
    const val POLE_TOP_LIGHT: Short = 1422 // Light Fixture subtype
    const val SPOTLIGHT: Short = 1423 // Light Fixture subtype
    const val LINEAR_LIGHT: Short = 1424 // Light Fixture subtype
    const val STREET_LIGHT: Short = 1425 // Light Fixture subtype
    const val SHELVES_LIGHT: Short = 1426 // Light Fixture subtype
    const val HIGH_BAY_OR_LOW_BAY_LIGHT: Short = 1427 // Light Fixture subtype
    const val EMERGENCY_EXIT_LIGHT: Short = 1428 // Light Fixture subtype
    const val GENERIC_FAN: Short = 1472 // Generic category
    const val CEILING_FAN: Short = 1473 // Fan subtype
    const val AXIAL_FAN: Short = 1474 // Fan subtype
    const val EXHAUST_FAN: Short = 1475 // Fan subtype
    const val PEDESTAL_FAN: Short = 1476 // Fan subtype
    const val DESK_FAN: Short = 1477 // Fan subtype
    const val WALL_FAN: Short = 1478 // Fan subtype
    const val GENERIC_HVAC: Short = 1536 // Generic category
    const val THERMOSTAT: Short = 1537 // HVAC subtype
    const val GENERIC_AIR_CONDITIONING: Short = 1600 // Generic category
    const val GENERIC_HUMIDIFIER: Short = 1664 // Generic category
    const val GENERIC_HEATING: Short = 1728 // Generic category
    const val RADIATOR: Short = 1729 // Heater subtype
    const val BOILER: Short = 1730 // Heater subtype
    const val HEAT_PUMP: Short = 1731 // Heater subtype
    const val INFRARED_HEATER: Short = 1732 // Heater subtype
    const val RADIANT_PANEL_HEATER: Short = 1733 // Heater subtype
    const val FAN_HEATER: Short = 1734 // Heater subtype
    const val AIR_CURTAIN: Short = 1735 // Heater subtype
    const val GENERIC_ACCESS_CONTROL: Short = 1792 // Generic category
    const val ACCESS_DOOR: Short = 1793 // Access subtype
    const val GARAGE_DOOR: Short = 1794 // Access subtype
    const val EMERGENCY_EXIT_DOOR: Short = 1795 // Access subtype
    const val ACCESS_LOCK: Short = 1796 // Access subtype
    const val ELEVATOR: Short = 1797 // Access subtype
    const val WINDOW: Short = 1798 // Access subtype
    const val ENTRANCE_GATE: Short = 1799 // Access subtype
    const val GENERIC_MOTORIZED_DEVICE: Short = 1856 // Generic category
    const val MOTORIZED_GATE: Short = 1857 // Motorized subtype
    const val AWNING: Short = 1858 // Motorized subtype
    const val BLINDS_OR_SHADES: Short = 1859 // Motorized subtype
    const val CURTAINS: Short = 1860 // Motorized subtype
    const val SCREEN: Short = 1861 // Motorized subtype
    const val GENERIC_POWER_DEVICE: Short = 1920 // Generic category
    const val POWER_OUTLET: Short = 1921 // Power subtype
    const val POWER_STRIP: Short = 1922 // Power subtype
    const val PLUG: Short = 1923 // Power subtype
    const val POWER_SUPPLY: Short = 1924 // Power subtype
    const val LED_DRIVER: Short = 1925 // Power subtype
    const val FLUORESCENT_LAMP_GEAR: Short = 1926 // Power subtype
    const val HID_LAMP_GEAR: Short = 1927 // Power subtype
    const val GENERIC_LIGHT_SOURCE: Short = 1984 // Generic category
    const val INCANDESCENT_LIGHT_BULB: Short = 1985 // Light subtype
    const val LED_BULB: Short = 1986 // Light subtype
    const val HID_LAMP: Short = 1987 // Light subtype
    const val FLUORESCENT_LAMP: Short = 1988 // Light subtype
    const val LED_ARRAY: Short = 1989 // Light subtype
    const val MULTI_COLOR_LED_ARRAY: Short = 1990 // Light subtype
    const val GENERIC_PULSE_OXIMETER: Short = 3136 // Pulse Oximeter Generic Gategory
    const val FINGERTIP: Short = 3137 // Pulse Oximeter subtype
    const val WRIST_WORN: Short = 3138 // Pulse Oximeter subtype
    const val GENERIC_WEIGHT_SCALE: Short = 3200 // Weight Scale Generic Category
    const val GENERIC_PERSONAL_MOBILITY_DEVICE: Short = 3264 // Personal Mobility Device
    const val POWERED_WHEELCHAIR: Short = 3265 // Personal Mobility Device
    const val MOBILITY_SCOOTER: Short = 3266 // Personal Mobility Device
    const val GENERIC_CONTINUOUS_GLUCOSE_MONITOR: Short = 3328 // Continuous Glucose Monitor
    const val GENERIC_OUTDOOR_SPORTS_ACTIVITY: Short = 5184 // Outdoor Sports Activity Generic Category
    const val LOCATION_DISPLAY_DEVICE: Short = 5185 // Outdoor Sports Activity subtype
    const val LOCATION_AND_NAVIGATION_DISPLAY_DEVICE: Short = 5186 // Outdoor Sports Activity subtype
    const val LOCATION_POD: Short = 5187 // Outdoor Sports Activity subtype
    const val LOCATION_AND_NAVIGATION_POD: Short = 5188 // Outdoor Sports Activity subtype
}
